import Colors from './Colors';
import {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  SAFE_AREA_PADDING,
  CAPTURE_BUTTON_SIZE,
  CONTENT_SPACING,
  CONTROL_BUTTON_SIZE,
  MAX_ZOOM_FACTOR,
} from './CameraSize';

export {
  Colors,
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  SAFE_AREA_PADDING,
  CAPTURE_BUTTON_SIZE,
  CONTENT_SPACING,
  CONTROL_BUTTON_SIZE,
  MAX_ZOOM_FACTOR,
};
